on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
    - run: node --version
    - run: npm --version
    - name: get runner ip 
      run: curl https://api.ipify.org
    - uses: actions/checkout@v3
    - run: npm install
    - run: node app.js
