name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - name: node install
        run: node app.js

      
      - name: npm run
        run: npm run 
      - name: npm start 
        run: npm start
  
      - name: Test (Jest)
        run: npm run test

      - name: Build
        run: npm run build